// Article index — auto-generated by ED's publish module
import index from '../content/index.json'

// Explicit article body imports (generated by ED)
const articleBodies = import.meta.glob('../content/*.md', { eager: true, query: '?raw', import: 'default' })

export function getAllArticles() {
  return [...index].sort((a, b) =>
    new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0)
  )
}

export function getArticle(slug) {
  const meta = index.find(a => a.slug === slug)
  if (!meta) return null

  const bodyPath = `../content/${slug}.md`
  const body = articleBodies[bodyPath] || ''

  return {
    ...meta,
    body: stripFrontmatter(body),
  }
}

function stripFrontmatter(raw) {
  if (!raw) return ''
  return raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n*/, '')
}
